# Generated by Django 5.2 on 2025-05-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_remove_activitysuppliercities_supplier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
