# Generated by Django 5.2 on 2025-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_operationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationfile',
            name='file_type',
            field=models.CharField(choices=[('Çince Operasyon', 'Çince Operasyon'), ('Aktivite Belgeleri', 'Aktivite Belgeleri'), ('Rehber Belgeleri', 'Rehber Belgeleri'), ('Araç Görselleri', 'Araç Görselleri'), ('Araç Temizlik', 'Araç Temizlik'), ('Otopark', 'Otopark'), ('Yemek Fişi', 'Yemek Fişi'), ('Otel Dekont', 'Otel Dekont'), ('Uçuş Biletleri', 'Uçuş Biletleri'), ('Balon Dekontları', 'Balon Dekontları'), ('Tekne Biletleri', 'Tekne Biletleri'), ('Müze Biletleri', 'Müze Biletleri'), ('Otel Konfirme Mektubu', 'Otel Konfirme Mektubu'), ('Diğer Belgeler', 'Diğer Belgeler')], max_length=255, verbose_name='Dosya Tipi'),
        ),
    ]
