# Generated by Django 5.1.7 on 2025-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0005_alter_operationfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="payment_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Havale", "Havale"),
                    ("Xctrip", "Xctrip"),
                    ("Usdt", "Usdt"),
                    ("Kredi kartı", "Kredi kartı"),
                    ("Musa Weixin pay", "Musa Weixin pay"),
                    ("Nur weixin pay", "Nur weixin pay"),
                    ("Nur Alipay", "Nur Alipay"),
                    ("Musa Alipay", "Musa Alipay"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Ödeme Kanalı",
            ),
        ),
    ]
