# Generated by Django 5.1.7 on 2025-05-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0006_alter_operation_payment_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationitem",
            name="activity_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                db_index=True,
                default="No",
                max_length=20,
                verbose_name="Activite Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="activity_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Kayıtlı Aktivite Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="activity_sell_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Aktivite Satış Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="driver",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Şoför",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="eur_cost_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="EUR Maliyet Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="guide_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Rehber Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="guide_sell_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Rehber Satış Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="guide_var",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                db_index=True,
                default="No",
                max_length=20,
                verbose_name="Rehber var mı?",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="hotel_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                db_index=True,
                default="No",
                max_length=20,
                verbose_name="Otel Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="hotel_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Otel Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="hotel_sell_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Otel Satış Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="is_processed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="İşlendi mi?"
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="manuel_vehicle_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Manuel Araç Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                db_index=True,
                default="No",
                max_length=20,
                verbose_name="Müze Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum_person",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="Kişi Sayısı"
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Müze Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum_sell_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Müze Satış Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="other_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Diğer",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="other_sell_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Diğer Satış",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="pick_time",
            field=models.TimeField(
                blank=True, db_index=True, null=True, verbose_name="Alış Saati"
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="plaka",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Plaka",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="rmb_cost_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="RMB Maliyet Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="room_type",
            field=models.CharField(
                blank=True,
                choices=[("Tek", "Tek"), ("Cift", "Çift"), ("Uc", "Üç")],
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="Oda Türü",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="tl_cost_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="TL Maliyet Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="usd_cost_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="USD Maliyet Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="vehicle_price",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Araç Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="vehicle_sell_currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                db_index=True,
                default="TL",
                max_length=3,
                verbose_name="Araç Satış Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="vehicle_sell_price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Araç Satış Ücreti",
            ),
        ),
        migrations.AddIndex(
            model_name="operationitem",
            index=models.Index(
                fields=["company", "day", "operation_type"],
                name="tour_operat_company_794b43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operationitem",
            index=models.Index(
                fields=["company", "is_delete", "is_processed"],
                name="tour_operat_company_0c9460_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operationitem",
            index=models.Index(
                fields=["pick_time", "release_time"],
                name="tour_operat_pick_ti_9108a5_idx",
            ),
        ),
    ]
